### PR TITLE
New registration ref: #64

### PR DESCRIPTION
**Pull request by cortho**
see https://github.com/owncloud/guests/issues/64
I tried to implement in the least intrusive way and not to change the previous behavior too much.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@cortho thanks a lot - can you please adjust the failing tests as well?

**Comment by cortho** [comment]
yeah, I just saw them failing ... work in progress

**Comment by pmaier1** [comment]
@davitol FYI

**Comment by davitol** [comment]
@cortho Thank you for your PR. 

I have tried to add a new guest user and it seems to not behave as before.

**Steps**

1. Switch my owncloud Server to this branch
2. Enable guests app
3a. In the sharing menu type ```davitol@yahoo.es``` or ```davitol```...

3b. In sharing menu, create a guest group
4. In users menu, try to create a user in this group

In both situations I was not able to create a guest user.

Can you please give any hints about how to create it with your PR?

Thanks

screen shot 2017-07-14 at 11 05 44

**Comment by cortho** [comment]
This should not happen. Are you sure you built the app? This happened to me before: https://github.com/owncloud/guests/issues/101
Anyway, I'm cloning a fresh instance from github and re-check.

**Comment by cortho** [comment]
@davitol I did a recheck and everything went fine.

maybe you didn't clone the new_registration branch?

here are my steps:

[created mysql db and apache alias for /var/www/prtest]

cd /var/www/
git clone git@github.com:owncloud/core.git prtest
cd prtest/apps
git clone -b new_registration git@github.com:cortho/guests.git
cd guests
npm install
webpack
cd /var/www/prtest
make
sudo chown -R www-data:www-data /var/www/prtest
sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "prtest" --database-user "owncloud" --database-pass "********" --admin-user "admin" --admin-pass "****"
sudo -u www-data php occ app:enable guests

browser: localhost/prtest, login as admin
when I open the sharetabview for welcome.txt I enter guest@localhost into the input field and the option "Add guest@localhost (guest)" pops up

**Comment by davitol** [comment]
@cortho Thanks for checking

> maybe you didn't clone the new_registration branch?

Yes, that's what i did and I have checked your code is included in my server.

I will retry and tell you.

Another question, are nicknames supported now as guest users? or it is only accepted an email in sharetabview for creating a guest user.

**Comment by cortho** [comment]
In accordance with https://github.com/owncloud/guests/issues/58 guest users are now created by their email addresses.

**Comment by davitol** [comment]
> cd guests
> npm install
> webpack

But these steps should be included in a Makefile file no? I mean, I expect to download the code at it will be ready for using or just run make and go.

@DeepDiver1975 @cortho

**Comment by DeepDiver1975** [comment]
> But these steps should be included in a Makefile file no? I mean, I expect to download the code at it will be ready for using or just run make and go.

yes - the makefile is missing ..... we can do this in another pr ..

**Comment by cortho** [comment]
what is the status here?
@pmaier  @IljaN

**Comment by davitol** [comment]
Test results here: https://github.com/owncloud/QA/issues/472

LGTM 👍

**Comment by pmaier1** [comment]
> Another question, are nicknames supported now as guest users? or it is only accepted an email in sharetabview for creating a guest user.

Both needs to be possible! 
- insert a 'name' in sharetabview 
-> Add 'name' (guest)
- insert mail address in sharetabview
-> mail@address.tld (guest)
-> mail@address.tld (remote)

> what is the status here?

Are there other open questions?

**Comment by davitol** [comment]
@cortho @pmaier1 Should we merge this PR and then Re-add the scenario in other PR?

> insert a 'name' in sharetabview
> -> Add 'name' (guest)

or should we include this here before merging?

**Comment by pmaier1** [comment]
> @cortho @pmaier1 Should we merge this PR and then Re-add the scenario in other PR?

That's up to you. Probably do a second PR to bring back the functionality.

**Comment by cortho** [comment]
This is only a minor change, I can do this in the afternoon.

**Comment by cortho** [comment]
done, but I didn't get the focus for the empty fields working. maybe some vue-guru can assist later.

**Comment by felixboehm** [comment]
@felixheidecke can you help fixing some vue frontend issues here, please.

**Comment by davitol** [comment]
👍 LGTM for merging @cortho @pmaier1 


Kindly remember:

> yes - the makefile is missing ..... we can do this in another pr ..

https://github.com/owncloud/guests/issues/104

Screenshot about how empty name is shown now:

screen shot 2017-08-10 at 13 43 13
screen shot 2017-08-10 at 13 43 28

**Comment by pmaier1** [comment]
Nice :+1: Please merge when you're fine with it. We will include this in the upcoming release of the guests app. This is the last open PR for the release.

>  Screenshot about how empty name is shown now:

A solution to this would be good. Maybe the modal does not need to appear at all when entering a mail address directly. Guests can choose their display name themselves if needed, otherwise the mail address is used, right?

**Comment by cortho** [comment]
@pmaier1 I'm looking forward to a fast release as well, so I'll only have a look at the {name} issue and hopefully can provide a solution this afternoon.

I didn't manage to fix the focus issue from above (the vue/jquery connection gave me cold shivers), however this could be considerated as a minor usability glitch, which could be done in a subsequent issue.

**Comment by pmaier1** [comment]
> @pmaier1 I'm looking forward to a fast release as well, so I'll only have a look at the {name} issue and hopefully can provide a solution this afternoon.

Perfect, thanks!

**Comment by cortho** [comment]
@pmaier1 I found out, this can easily be done, but I see multiple possiblilites for the title:
 1. only show _Share with guest_ and never display any more information
 2. only show the _Share with guest_ + Name, when one is entered, display _Share with guest_ when no name is entered
 3. same as above, but with the email address
 4. always prefill Name with the email address, when guest was entered as an email address

What do you think?

**Comment by pmaier1** [comment]
> @pmaier1 I found out, this can easily be done, but I see multiple possiblilites for the title:

- Guest account initiated by entering a name
-> Display 'Share with guest 'Name'' as is
- Guest account initiated by entering a mail address
-> Display 'Share with guest 'mail address''
This should be option 4, I guess. Not sure about the difference to option 3.
The inviting user can still set a display name if he wants to. I think this is fine.

**Comment by cortho** [comment]
@pmaier1 modified title generation for the modal window. who'll check this, you or @davitol ?
I'll merge, when you think this is fine now.

**Comment by cortho** [comment]
Somebody can tell, why the travis build failed? I don't really see a reason in the details. Timeout?

**Comment by pmaier1** [comment]
@davitol please re-review with the latest changes!

**Comment by davitol** [comment]
> Somebody can tell, why the travis build failed? I don't really see a reason in the details. Timeout?

No composer.json in current directory, do you want to use the one at /home/travis/build/owncloud/core? [Y,n]? 

Maybe there is something wrong in the Travis Script. It keeps waiting for a an answer and Travis decides to abort

**Comment by cortho** [comment]
Thank you, I was not aware of this, I'll have a look, how the composer.json needs to look like.

Since this is not the first pitfall, is there any building documentation I missed?

**Comment by cortho** [comment]
@DeepDiver1975 As I am not so proficient with the build env - would you recomment to change the path to  core/composer.json or to remove the _cd_ and _composer install_ in _run.sh_ at all?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 As I am not so proficient with the build env - would you recomment to change the path to core/composer.json or to remove the cd and composer install in run.sh at all?

just remove the composer call at this location ... should all me good then ... lets see ;-)

**Comment by cortho** [comment]
@davitol @pmaier1 test has passed, nothing more to do from my side.

can be merged, when approved.

**Comment by pmaier1** [comment]
> @davitol @pmaier1 test has passed, nothing more to do from my side.

Nice, thanks!

@davitol for final review pls. Then merge and we are ready set for the release!

**Comment by davitol** [comment]
Sharing a file with a guest user I get the following screen and log when the guest user wants to access to the file:

screen shot 2017-08-16 at 16 12 04


```
{"reqId":"BoWjd5BrPrApWxLbFGYc","level":2,"time":"2017-08-16T14:08:54+00:00","remoteAddr":"85.57.168.79","user":"dtoledo@solidgear.es","app":"filesystem","method":"GET","url":"\/remote.php\/webdav\/remote.php\/dav\/files\/dtoledo%40solidgear.es\/Paris.jpg","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
```

Seems the guest user can open the files even when the whitelist includes e.g gallery

screen shot 2017-08-16 at 16 13 33

**Comment by davitol** [comment]
I've realized that there was a comma in the beginning of the whitelist. Reseting whitelist I'm also not able to access to the resources shared:

```
{"reqId":"eAN4B17fQrWpCSO5FkNe","level":2,"time":"2017-08-16T15:16:04+00:00","remoteAddr":"85.57.168.79","user":"dtoledo@mymail.es","app":"no app in context","method":"POST","url":"\/index.php\/login?user=David","message":"Skeleton not created due to missing write permission"}
```

**Comment by cortho** [comment]
omg. I'll investigate this.

**Comment by cortho** [comment]
stupid mistake, a comma was missing .,,

@davitol if you would be so kind retesting this (I hope for the last time)? ... and fyi: the comma, core and files was moved to the backend in https://github.com/owncloud/guests/pull/127

**Comment by davitol** [comment]
@cortho Keeps failing. I've created a guest user via mail, sharing a .png file that admin user is able to open. Gallery app is included in the whitelist but when I log in with the guest user, he is not able to open the image.

```
{"reqId":"bbJ6ejYwo1wQSA2jPwB6","level":2,"time":"2017-08-17T09:14:33+00:00","remoteAddr":"85.57.168.79","user":"dtoledo@solidgear.es","app":"filesystem","method":"GET","url":"\/remote.php\/webdav\/remote.php\/dav\/files\/dtoledo%40solidgear.es\/1501242506.png","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
```

**Comment by cortho** [comment]
very strange. @davitol, thx for your efforts, I'll go into debugging

**Comment by cortho** [comment]
Current status: wfm with 10.0.2

**Comment by PVince81** [comment]
@cortho would you be able to git bisect core to find out when it stopped working ? Then we can find out what commit caused it and find who to talk to...

**Comment by cortho** [comment]
@PVince81 sure, I'l try to find out

**Comment by cortho** [comment]
@PVince81 good news: this issue does not occur with tags/v10.0.3beta but only with (current) master.
This is the commit which breaks functionality for the guests app and for shibboleth users as well, as @davitol found out
https://github.com/owncloud/core/commit/17840e724ba77e28f80d83bde90db52620926569

**Comment by PVince81** [comment]
Okay, I'll have a look... I was wondering whether we should backport that commit, good thing we didn't...

Does it mean this PR can be merged then ?

**Comment by PVince81** [comment]
I wanted to debug the issue you mentioned but somehow I can't create the guest in the first place, steps:

1. Checkout core master
1. Checkout guests master
1. `git checkout -b cortho-new_registration master`
1. `git pull https://github.com/cortho/guests.git new_registration`
1. `occ app:enable guests`
1. Create a folder "test"
1. Share "test" with "v p (guest)"
1. Type in "vincent@local"
1. Click "Share"

spectacle l10435

OCS respnse is `"{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Please specify a valid user"},"data":[]}}"`

Also happens with a valid email.

@cortho how did you test ?

**Comment by PVince81** [comment]
If I switch back to guests master and click "Share" it goes through. So there is something broken in this PR.

**Comment by PVince81** [comment]
Ok, on master there is a bug if a user id contains an "@", not related directly to guests app but since guests often have an "@" in their user id, it triggers it. Raised here, I'll have a look: https://github.com/owncloud/core/issues/28730. You can ignore this issue now as this works on stable10.

@cortho please investigate https://github.com/owncloud/guests/pull/109#issuecomment-323091261

**Comment by davitol** [comment]
> yes - the makefile is missing ..... we can do this in another pr ..

Works for me in 10.0.3beta version so I feel fine about merging this PR. The makefile should be done in another PR

**Comment by PVince81** [comment]
@cortho I forgot to run make/webpack, ignore my errors.

**Comment by cortho** [comment]
@PVince81 np, @davitol pointed it out to me. I'ts really about time for the makefile. Ill look, what I can do.

**Comment by cortho** [comment]
This closes #58, closes #69, closes #82, closes #88, closes #89, closes #93

**Comment by PVince81** [comment]
@cortho 🔔🥇6X COMBO

**Comment by pmaier1** [comment]
Yeah, nice, guys! Good job!

**Pull request merged**
