### PR TITLE
[WIP] Remove user_autofocus expectation from paramters list

### PR DESCRIPTION
**Pull request by sharidas**
Add user_autofocus to the parameter list to fix
the error thrown in the logs.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
fixes https://github.com/owncloud/guests/issues/236

**Comment by sharidas** [comment]
As of now I have tried to get rid of the error from log. And this code is WIP. Below are the steps which need to be done.

- [ ] analyze why this change was missing and compare with old version 10.0.8

**Comment by PVince81** [comment]
did you grep for "user_autofocus" in core ? maybe that template was copied from core and had it.

**Comment by sharidas** [comment]
Yes, I found the `user_autofocus` in the core at https://github.com/owncloud/core/blob/master/core/templates/login.php#L48 and https://github.com/owncloud/core/blob/master/core/templates/login.php#L58

This was the first step I did. Found it at login.php and logincontroller. And then made a WIP PR. @PVince81

**Comment by sharidas** [comment]
Indeed the `user_autofocus` is not required here. The user name field is already filled with the email id. The only field which needs user attention or required to be filled is the password. So we can remove this safely and autofocus on the password by default. I have updated the pr.

**Pull request merged**
