### PR TITLE
adapt CHANGELOG.md for #140

### PR DESCRIPTION
**Pull request by cortho**
I was using the _GitHub Changelog Generator_ and stripped all _not notable_ entries, for older releases just adjusted the .md syntax

### CODE REVIEW

**Comment by PVince81** [comment]
Links are missing: every version text links to the commit diff, see the raw text in the text area in  http://keepachangelog.com/en/1.0.0/ and scroll down to the bottom

**Comment by cortho** [comment]
Thank you, I missed that. -> updated

**Comment by PVince81** [comment]
> GitHub Changelog Generator 

Ah yes, I tried this tool for core and it crashed because there are too many tickets there.

Also, today I learnt: `\#1234` to link to local github tickets within a markdown file. Great.

**Comment by cortho** [comment]
@PVince81 sry, I had to fix the links, they led to tree instead of compare

My commit does not show up here: https://github.com/owncloud/guests/compare/master...cortho:0.4.2-changelog - is this because the PR was already merged? Do I have to create a new PR for this?

**Comment by PVince81** [comment]
Please make a new PR.

**Comment by cortho** [comment]
@PVince81 done, PR here: https://github.com/owncloud/guests/pull/144

**Pull request merged**
