### PR TITLE
[Tests-Only] enforce strict type checking in acceptace tests code

### PR DESCRIPTION
**Pull request by dpakach**
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code

**note** this PR was generated by a automated script

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIGuest-latest-firefox-postgres9.4-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/guests/2156/25/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiGuests-master-postgres9.4-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/guests/2157/28/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIGuest-latest-chrome-oracle-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/guests/2158/23/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIGuest-master-firefox-postgres9.4-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/guests/2158/19/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiGuestsScality-master-mysql8.0-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/guests/2159/33/1

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
