### PR TITLE
Add extensionpoint to sharedialogview

### PR DESCRIPTION
**Pull request by felixheidecke**
Write method overriding extension

### CODE REVIEW

**Comment by PVince81** [comment]
Works for me, I put this line:
```js
OC.Plugins.register('OCA.Share.foo');
```

at the end of ShareDialogView.initialize().

A breakpoint inside https://github.com/owncloud/guests/pull/5/files#diff-41d794d24ff042b1f9ac211fc3f9f951R4 properly stops when I type something in the autocomplete dialog.

The problem you probably have is that `this` is not defined the same.
You need to use `obj` instead.
Or define an outside variable `var self = obj;` before line 3 here https://github.com/owncloud/guests/pull/5/files#diff-41d794d24ff042b1f9ac211fc3f9f951R3.

**Comment by PVince81** [comment]
ah, or replace `var view = this;` with `var view = obj;` here https://github.com/owncloud/guests/pull/5/files#diff-41d794d24ff042b1f9ac211fc3f9f951R4

And `this.$el.` with `view.$el.`

**Comment by PVince81** [comment]
Or an even more advanced technique, add this at the end of `attach`:

```js
_.bind(obj.autocompleteHandler, obj);
```

This will make sure that `this` is actually `obj` when used inside your `autocompleteHandler`.

**Comment by felixheidecke** [comment]
@PVince81 **thx!** I didn't realize that `this` wouldn't refer to the current object :sweat_smile:

> Works for me, I put this line:
> OC.Plugins.register('OCA.Share.foo');
> at the end of ShareDialogView.initialize().

I think you forgot to pass `this` in the register method, otherwise, there will be nothing to extend :clap:

**Pull request closed without merging**
