### PR TITLE
allow setting share block domains in admin panel

### PR DESCRIPTION
**Pull request by mrow4a**
fixes: https://github.com/owncloud/enterprise/issues/4990

Screenshot 2022-04-26 at 21 40 35

### CODE REVIEW

**Review by JanAckermann — APPROVED** [review]

**Comment by phil-davis** [comment]
The string value is supposed to be a comma-separated list. But I can put in spaces between domain names, and I can enter any characters at all (that do not look like domain names)

We could:
1) do some easy automatic formatting (e.g. replace whitespace with commas, trim whitespace at beginning and end)
2) add some text to say that a comma-separated list of domain names is expected to be entered
3) (optional?) process the domain names through some "reasonable" validator to confirm that they are "valid" (the validator needs to accept less usual things like an IP address, "localhost" etc so that test/development installations can try local things)

**Comment by mrow4a** [comment]
@phil-davis I am aware of points here, but in fact it was earlier agreed to do only CMD for this feature. However I noticed it was just easier to implement this than write docs. I think what you mention should be an issue in this repo. I will also add fixme in the code for this

**Comment by pmaier1** [comment]
needs documentation @mmattel @EParzefall

**Comment by pmaier1** [comment]
@mrow4a what will the user see if they enter a mail address with a domain that is on the block list?

**Pull request merged**
